### ISSUE TITLE
Login-Request-Example

### ISSUE THREAD

**Issue by thokari** [mickireh/tabtracker#1]
So geht es, https://curl.haxx.se/ ist ein Kommandozeilen-Programm zum Senden von HTTP-Requests. Sollte aber auch mit POSTMAN gehen, must eben den Request-Header so setzen wie angegeben. 
```
$ curl -X POST -H "Content-Type: application/json" localhost:8081/register -d '{"email": "email@example.com"}'
{"message":"Hello, User was registered"}
```

**Comment by mickireh** [comment]
22       message: `Hello ${res.body.email} User was registered`
auch hier? da soll ja dann email stehen

**Comment by mickireh** [comment]
Mit Zeile **21**
![grafik](https://user-images.githubusercontent.com/11478015/85424968-e15ea280-b578-11ea-932e-07ef617848bf.png)

![grafik](https://user-images.githubusercontent.com/11478015/85425111-0d7a2380-b579-11ea-8112-7d43598ebf91.png)

**Comment by thokari** [comment]
Alles klar, hab's verstanden.

**Comment by mickireh** [comment]
Mit Zeile **22**
![grafik](https://user-images.githubusercontent.com/11478015/85425182-28e52e80-b579-11ea-9973-928afdad685b.png)

![grafik](https://user-images.githubusercontent.com/11478015/85425219-34d0f080-b579-11ea-984b-f50390b8cf7f.png)

**Comment by thokari** [comment]
Uh oh..
Es muß heißen `req.body` nicht `res.body`, der Request-Body ist ja im Request, dem eingehenden, nicht in der Response, der ausgehenden.
